pipeline:
  load:
    image: jbergknoff/postgresql-client
    secrets: [ pgport, pgpassword, pguser, pgdatabase, pghost ]
    commands:
      - apk --update add wget bash
      - bash committees.sh

  # slack:
  #   image: plugins/slack
  #   secrets: [ slack_webhook ]
  #   when:
  #     status: [ success, failure ]
  #   template: >
  #     {{#success build.status}}
  #       published https://private.publicintegrity.org/radiation-sari-graphic/
  #     {{else}}
  #       failed publishing https://private.publicintegrity.org/radiation-sari-graphic/
  #     {{/success}}
