pipeline:
  load-committees:
    image: publicintegrity/loader
    secrets: [ pgport, pgpassword, pguser, pgdatabase, pghost, cycles ]
    commands:
      - cd /committees
      - bash load.sh

  load-candidates:
    image: publicintegrity/loader
    secrets: [ pgport, pgpassword, pguser, pgdatabase, pghost, cycles ]
    commands:
      - cd /candidates
      - bash load.sh

  load-pac-summaries:
    image: publicintegrity/loader
    secrets: [ pgport, pgpassword, pguser, pgdatabase, pghost, cycles ]
    commands:
      - cd /pac_summaries
      - bash load.sh

  slack:
    image: plugins/slack
    secrets: [ slack_webhook ]
    when:
      status: [ success, failure ]
