pipeline:
  load-committees:
    image: publicintegrity/loader
    secrets: [ pgport, pgpassword, pguser, pgdatabase, pghost ]
    commands:
      - bash committees/load.sh

  load-candidates:
    image: publicintegrity/loader
    secrets: [ pgport, pgpassword, pguser, pgdatabase, pghost ]
    commands:
      - bash candidates/load.sh

  load-pac-summaries:
    image: publicintegrity/loader
    secrets: [ pgport, pgpassword, pguser, pgdatabase, pghost ]
    commands:
      - bash pac_summaries/load.sh

  slack:
    image: plugins/slack
    secrets: [ slack_webhook ]
    when:
      status: [ success, failure ]
